/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/wallet/test-grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Test Grant
         * @description Development-only test credit grant; production returns 404.
         */
        post: operations["create_test_grant_v1_wallet_test_grants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LedgerPostingOut */
        LedgerPostingOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Unit */
            unit: string;
            /** Amount Ms */
            amount_ms: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LedgerTransactionOut */
        LedgerTransactionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Tx Type */
            tx_type: string;
            /** Idempotency Key */
            idempotency_key: string;
            /** Reference Type */
            reference_type: string;
            /** Reference Id */
            reference_id: string;
            /** Unit */
            unit: string;
            /** Metadata Json */
            metadata_json: {
                [key: string]: unknown;
            };
            /** Postings */
            postings?: components["schemas"]["LedgerPostingOut"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** TestGrantCreate */
        TestGrantCreate: {
            /** Tier */
            tier: string;
            /** Amount Ms */
            amount_ms: number;
            /** Idempotency Key */
            idempotency_key: string;
            /** Reason */
            reason: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_test_grant_v1_wallet_test_grants_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestGrantCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerTransactionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
