/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_v1_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_v1_projects__project_id__delete"];
        options?: never;
        head?: never;
        /** Update Project */
        patch: operations["update_project_v1_projects__project_id__patch"];
        trace?: never;
    };
    "/v1/projects/{project_id}/shots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Shots */
        get: operations["list_shots_v1_projects__project_id__shots_get"];
        put?: never;
        /** Create Shot */
        post: operations["create_shot_v1_projects__project_id__shots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shots/{shot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Shot */
        get: operations["get_shot_v1_shots__shot_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Shot */
        patch: operations["update_shot_v1_shots__shot_id__patch"];
        trace?: never;
    };
    "/v1/shots/{shot_id}/references": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Shot Reference */
        post: operations["create_shot_reference_v1_shots__shot_id__references_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shots/{shot_id}/references/{reference_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Shot Reference */
        delete: operations["delete_shot_reference_v1_shots__shot_id__references__reference_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Asset */
        post: operations["upload_asset_v1_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Project Asset */
        post: operations["upload_project_asset_v1_projects__project_id__assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assets/{asset_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Asset */
        get: operations["download_asset_v1_assets__asset_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Generation Quote */
        post: operations["create_generation_quote_v1_quotes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallet/test-grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Test Grant */
        post: operations["create_test_grant_v1_wallet_test_grants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Wallet */
        get: operations["get_wallet_v1_wallet_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ledger Transactions */
        get: operations["list_ledger_transactions_v1_ledger_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate */
        post: operations["generate_v1_generations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/generations/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Generation */
        get: operations["get_generation_v1_generations__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/generations/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Generation */
        post: operations["cancel_generation_v1_generations__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_v1_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/outputs/{output_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Output */
        get: operations["download_output_v1_outputs__output_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AttemptStatus
         * @enum {string}
         */
        AttemptStatus: "CREATED" | "SUBMITTING" | "SUBMITTED" | "RUNNING" | "SUCCEEDED" | "FAILED_RETRYABLE" | "FAILED_FINAL" | "CANCELLED" | "TIMED_OUT";
        /** Body_upload_asset_v1_uploads_post */
        Body_upload_asset_v1_uploads_post: {
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** Body_upload_project_asset_v1_projects__project_id__assets_post */
        Body_upload_project_asset_v1_projects__project_id__assets_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** GenerationAttemptOut */
        GenerationAttemptOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Attempt No */
            attempt_no: number;
            /** Provider Code */
            provider_code: string;
            status: components["schemas"]["AttemptStatus"];
            /** Provider Job Id */
            provider_job_id: string | null;
            /** Workflow Version */
            workflow_version: string;
            /** Failure Code */
            failure_code: string | null;
        };
        /** GenerationCreate */
        GenerationCreate: {
            /**
             * Shot Id
             * Format: uuid
             */
            shot_id: string;
            /**
             * Quote Id
             * Format: uuid
             */
            quote_id: string;
            /**
             * Mock Mode
             * @default success
             * @enum {string}
             */
            mock_mode: "success" | "delayed" | "failure" | "timeout" | "duplicate" | "corrupt";
        };
        /** GenerationJobList */
        GenerationJobList: {
            /** Items */
            items: components["schemas"]["GenerationJobOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** GenerationJobOut */
        GenerationJobOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Shot Id
             * Format: uuid
             */
            shot_id: string;
            /** Tier Code */
            tier_code: string;
            /** Duration Ms */
            duration_ms: number;
            /** Resolution */
            resolution: string;
            /** Aspect Ratio */
            aspect_ratio: string;
            /** Variant Index */
            variant_index: number;
            /** Quote Id */
            quote_id: string | null;
            /** Quote Snapshot */
            quote_snapshot?: {
                [key: string]: unknown;
            };
            /** Ledger Unit */
            ledger_unit: string | null;
            /** Reserved Ms */
            reserved_ms?: number | null;
            settlement_status: components["schemas"]["SettlementStatus"] | null;
            status: components["schemas"]["JobStatus"];
            /** Final Output Id */
            final_output_id: string | null;
            /** Failure Code */
            failure_code: string | null;
            /** Error Message */
            error_message: string | null;
            /** Mock Mode */
            mock_mode: string;
            /** Attempts */
            attempts?: components["schemas"]["GenerationAttemptOut"][];
            /** Outputs */
            outputs?: components["schemas"]["GenerationOutputOut"][];
            /** Events */
            events?: components["schemas"]["JobEventOut"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** GenerationOutputOut */
        GenerationOutputOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Attempt Id
             * Format: uuid
             */
            attempt_id: string;
            /** Media Type */
            media_type: string;
            /** Duration Ms */
            duration_ms: number | null;
            /** Width */
            width: number | null;
            /** Height */
            height: number | null;
            /** Fps */
            fps: number | null;
            /** Codec */
            codec: string | null;
            /** Size Bytes */
            size_bytes: number;
            /** Sha256 */
            sha256: string;
            validation_status: components["schemas"]["OutputValidationStatus"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobEventOut */
        JobEventOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Attempt Id */
            attempt_id: string | null;
            /** Event Type */
            event_type: string;
            /** From Status */
            from_status: string | null;
            /** To Status */
            to_status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "CREATED" | "RESERVED" | "QUEUED" | "ROUTING" | "SUBMITTED" | "RUNNING" | "POSTPROCESSING" | "VALIDATING" | "SUCCEEDED" | "FAILED_FINAL" | "CANCELLED" | "EXPIRED" | "REJECTED_POLICY";
        /** LedgerPostingOut */
        LedgerPostingOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Unit */
            unit: string;
            /** Amount Ms */
            amount_ms: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LedgerTransactionList */
        LedgerTransactionList: {
            /** Items */
            items: components["schemas"]["LedgerTransactionOut"][];
        };
        /** LedgerTransactionOut */
        LedgerTransactionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Tx Type */
            tx_type: string;
            /** Idempotency Key */
            idempotency_key: string;
            /** Reference Type */
            reference_type: string;
            /** Reference Id */
            reference_id: string;
            /** Unit */
            unit: string;
            /** Metadata Json */
            metadata_json: {
                [key: string]: unknown;
            };
            /** Postings */
            postings?: components["schemas"]["LedgerPostingOut"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * OutputValidationStatus
         * @enum {string}
         */
        OutputValidationStatus: "PENDING" | "VALID" | "INVALID";
        /** ProjectAssetOut */
        ProjectAssetOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Original Filename */
            original_filename: string;
            /** Media Type */
            media_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Sha256 */
            sha256: string;
            status: components["schemas"]["ProjectAssetStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ProjectAssetStatus
         * @enum {string}
         */
        ProjectAssetStatus: "READY" | "DELETED";
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** ProjectList */
        ProjectList: {
            /** Items */
            items: components["schemas"]["ProjectOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** ProjectOut */
        ProjectOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProjectUpdate */
        ProjectUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
        };
        /** QuoteCreate */
        QuoteCreate: {
            /**
             * Shot Id
             * Format: uuid
             */
            shot_id: string;
            /** Tier */
            tier: string;
            /**
             * Resolution
             * @default 720P
             */
            resolution: string;
            /**
             * Variant Count
             * @default 1
             */
            variant_count: number;
        };
        /** QuoteOut */
        QuoteOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Shot Id
             * Format: uuid
             */
            shot_id: string;
            /**
             * Price Version Id
             * Format: uuid
             */
            price_version_id: string;
            /** Tier Code */
            tier_code: string;
            /** Billing Unit */
            billing_unit: string;
            /** Duration Ms */
            duration_ms: number;
            /** Variant Count */
            variant_count: number;
            /** Resolution */
            resolution: string;
            /** Aspect Ratio */
            aspect_ratio: string;
            /** Reserved Ms */
            reserved_ms: number;
            status: components["schemas"]["QuoteStatus"];
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * QuoteStatus
         * @enum {string}
         */
        QuoteStatus: "OPEN" | "USED" | "EXPIRED";
        /**
         * SettlementStatus
         * @enum {string}
         */
        SettlementStatus: "RESERVED" | "SETTLED" | "RELEASED";
        /** ShotCreate */
        ShotCreate: {
            /** Title */
            title: string;
            /** Prompt */
            prompt: string;
            /** Duration Seconds */
            duration_seconds: number;
            /**
             * Aspect Ratio
             * @enum {string}
             */
            aspect_ratio: "16:9" | "9:16";
        };
        /** ShotList */
        ShotList: {
            /** Items */
            items: components["schemas"]["ShotOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** ShotOut */
        ShotOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Title */
            title: string;
            /** Prompt */
            prompt: string;
            /** Duration Seconds */
            duration_seconds: number;
            /** Aspect Ratio */
            aspect_ratio: string;
            /** References */
            references?: components["schemas"]["ShotReferenceOut"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ShotReferenceCreate */
        ShotReferenceCreate: {
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /** Reference Role */
            reference_role: string;
        };
        /** ShotReferenceOut */
        ShotReferenceOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /** Reference Role */
            reference_role: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ShotUpdate */
        ShotUpdate: {
            /** Title */
            title?: string | null;
            /** Prompt */
            prompt?: string | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Aspect Ratio */
            aspect_ratio?: ("16:9" | "9:16") | null;
        };
        /** TestGrantCreate */
        TestGrantCreate: {
            /** Tier */
            tier: string;
            /** Amount Ms */
            amount_ms: number;
            /** Idempotency Key */
            idempotency_key: string;
            /** Reason */
            reason: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WalletOut */
        WalletOut: {
            /** Balances */
            balances: {
                [key: string]: {
                    [key: string]: number;
                };
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_projects_v1_projects_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_v1_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_v1_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_shots_v1_projects__project_id__shots_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShotList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_shot_v1_projects__project_id__shots_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShotCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shot_v1_shots__shot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_shot_v1_shots__shot_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShotUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_shot_reference_v1_shots__shot_id__references_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShotReferenceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShotReferenceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_shot_reference_v1_shots__shot_id__references__reference_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shot_id: string;
                reference_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_asset_v1_uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_asset_v1_uploads_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectAssetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_project_asset_v1_projects__project_id__assets_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_project_asset_v1_projects__project_id__assets_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectAssetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_asset_v1_assets__asset_id__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_generation_quote_v1_quotes_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_test_grant_v1_wallet_test_grants_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestGrantCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerTransactionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_wallet_v1_wallet_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletOut"];
                };
            };
        };
    };
    list_ledger_transactions_v1_ledger_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerTransactionList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_v1_generations_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_generation_v1_generations__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_generation_v1_generations__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_v1_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJobList"];
                };
            };
        };
    };
    download_output_v1_outputs__output_id__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                output_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
